version: 2
updates:
  # Python dependencies - Production requirements
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    reviewers:
      - "x3dfxjunkie"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    reviewers:
      - "x3dfxjunkie"
